
    - name: Update the apt cache; unless it's been updated in the last 8 hours
      apt: update_cache=true  cache_valid_time=28800


    - name: Install Python
      apt: pkg=python-software-properties


    - name: Install Python
      apt: pkg=python


    - name: Install g++
      apt: pkg=g++


    - name: Installing make
      apt: pkg=make


    - name: Install git
      apt: pkg=git state=latest
