
    - name: Installing Bower (may take some time)
      command: npm install -g bower
      ignore_errors: yes

    - name: Installing Grunt-cli
      command: npm install -g grunt-cli

    - name: Ensure github is in the known_hosts file
      known_hosts: host=github.com state=present

    - name: Pulling down mean.js
      git: repo='https://github.com/meanjs/mean.git' dest=/home/vagrant/mean

    - name: Installing mean.js
      npm: path=/home/vagrant/mean/

